language: bash
sudo: required
services:
  - docker

env:
  matrix:
    - PHP_VERSION=7.2 BUILD_SERVICE=workspace
    - PHP_VERSION=7.2 BUILD_SERVICE=php-fpm


# Installing a newer Docker version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: ./travis-build.sh

branches:
  only:
  - general_environment_build


notifications:
  email: false
